#!/usr/bin/env python

from __future__ import print_function
from fileinput import input
import json

headers = None
count = 0

print('[')
for line in input():
    values = line.splitlines()[0].split(',')
    if headers is None:
        headers = values
    else:
        x = dict()
        for k,v in zip(headers, values):
            try:
                v = json.loads(v)
            except ValueError:
                pass
            x[k] = v
        if count > 0:
            print(',')
        print(json.dumps(x))
        count += 1
print(']')
