#!/usr/bin/env python

from __future__ import print_function
import csv
import json

def convert(input, output):
    reader = csv.DictReader(input)
    fieldnames = reader.fieldnames
    objects = []
    for x in reader:
        for k,v in x.items():
            try:
                v = json.loads(v)
            except ValueError:
                pass
            x[k] = v
        objects.append(x)
    json.dump(objects, output)

if __name__ == '__main__':
    import sys
    if len(sys.argv) > 1:
        print('Usage: {}\nConvert CSV (stdin) to JSON (stdout).'.format(sys.argv[0]), file=sys.stderr)
        sys.exit(1)
    convert(input=sys.stdin, output=sys.stdout)
